### ISSUE TITLE
configuration.yaml

### ISSUE THREAD

**Issue by jafreenas** [10der/homeassistant-custom_components-awtrix#3]
Hello, I have successfully integrated awtrix with hacs, I also added awtrix in the configuration.yaml. but I can't find the awtrix.notify service for example, do you have any ideas?

**Comment by puzz3d** [comment]
Hi @jafreenas 
The name of the notify service is **notify.awtrix_***, not awtrix.notify

**Comment by jafreenas** [comment]
well done

**Comment by Reaper2507** [comment]
cant find that either followed step by step too its integreated can change light and all but no notification
